name: Deploy using SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup SSH
      run: |
        mkdir C:\Users\spark.chang\.ssh
        echo "$env:SSH_PRIVATE_KEY" > C:\Users\runner\.ssh\id_rsa
        # Add any additional setup commands if needed

    - name: Transfer cxl_api folder
      run: |
        pscp -r C:\sele_tur user@220.134.146.222:/test_actions
